version: '3.8'

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tcc
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 13306:3306

  zk:
    image: zookeeper:3.6.2
    restart: always
    hostname: zk
    ports:
      - 12181:2181